import { Button, Htag, Paragraph, Rating, Tag } from '@/components';
import Head from 'next/head';
import { useState } from 'react';

export default function Home() {
  const [rating, setRating] = useState(4); 

  return (
    <>
      <Head>
        <title>Create Next App</title>
        <meta name="description" content="Generated by create next app" />
        <meta name="viewport" content="width=device-width, initial-scale=1" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <div>
        <Htag tag="h1">Home </Htag>
        <Button appearance='primary' arrow='down'>Add me</Button>
        <Paragraph size='l'>Large</Paragraph>
        <Paragraph>Middle</Paragraph>
        <Paragraph size='s'>Small</Paragraph>
        <Tag size='s' color="red">Tag</Tag>
      </div>
      <Rating rating={rating} isEditable setRating={setRating}></Rating>
    </>
  );
}
